### ISSUE TITLE
Migrate repository to sile-typesetter org?

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/casile#26]
Per [this issue](https://github.com/sile-typesetter/sile/issues/666] SILE has it's own [org namespace](https://github.com/sile-typesetter/) on Github now. It might make sense to migrate this there as well. It is not a dependency for SILE, nor does it even require SILE to use (only the PDF output option depends on SILE). But it was conceived as a framework for using SILE in a larger publishing workflow. Arguably Pandoc is actually more central to gluing everything together, I can't imagine extricating SILE either.

Thoughts @simoncozens?

**Comment by simoncozens** [comment]
Yes please!

**Comment by alerque** [comment]
@simoncozens Okay. Then I can hack on `alerque/casile` to my hearts content and hopefully not break other people's production by being more careful about what hits master on the org version.

**Comment by alerque** [comment]
@simoncozens One regression I didn't expect when migrating this repository is that I've lost access to the Github settings so I can't do things like fix branch protection or setup CI.

Would you mind bumping me to be an owner rather than a member of the Org so I can make repository setting changes?

**Comment by simoncozens** [comment]
Done!
