### ISSUE TITLE
Pass image width/height options

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/casile#36]
Trying to control the rendered size of images in a text, I used the "link attributes" syntax:

```
![Hand composition, by Wilhei on Wikipedia](concepts/512px-Handsatz.jpg){ width=120pt }
```

In LaTeX this renders to `\includegraphics[width=120pt]{concepts/512px-Handsatz.jpg}`, but the SILE writer only passes on:

```
\img[src=concepts/512px-Handsatz.jpg]
```

(Dropping the width and the caption.) The caption would be nice, but width/height attributes are essential.

**Comment by alerque** [comment]
Already fixed. Your build of Pandoc is out of date. Here is what the image markup should look like:

```sh
$ pandoc -t sile <<< '![caption](file.jpg){width=120pt}'
\Image[width=120pt,src=file.jpg,title=fig:]{caption}
```

Use the [sile-writer-pr](https://github.com/alerque/pandoc/tree/sile-writer-pr)  branch for best results, `make quick` to build. The [sile-head](https://github.com/alerque/pandoc/tree/sile-head) branch has a few more features I'm toying with (a Reader module, `+raw_sile` support, etc.) but the branch the PR branch is the one I'm targetting CaSILE towards right  now.
