### ISSUE TITLE
CaSILE quote environment not visually distinct

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/casile#43]
Here's an MWE:

```TeX
\begin[papersize=a5,class=book]{document}
\script[src=casile/casile]
Here is an unquoted paragraph. Lorem ipsum dolor sit amet, consectetur
adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua.

\begin{quote}
Here is a quoted paragraph. Lorem ipsum dolor sit amet, consectetur
adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua.
\end{quote}

\end{document}
```

![Screenshot 2020-03-02 at 09 14 29](https://user-images.githubusercontent.com/106728/75661970-3b53f900-5c66-11ea-87a9-7810b18ef0a9.png)

**Comment by simoncozens** [comment]
I would suggest: adding a 6pt skip before the quote; checking a setting `casile.quotesetback` or similar and setting the setback to that if it's present. (Assuming there's a good way to get settings into the document from the metadata.)

**Comment by alerque** [comment]
The CaSILE *quote* environment does have a setback presently defaulting to match `document.parindent`. I'm not sure why that isn't showing up in your screen shot. Time to test...

Long term this quote environment should just be upstreamed into SILE. I forget now exactly what the specific differences were that prompted me to setup such an over-ride.

**Comment by alerque** [comment]
Something is more seriously wrong there than tweaking the quote style. It has styles and they should have worked. I just messed around a bit and came up with a1d65715d0039e7d4b8ceb1b88cc61f003cd8da7 which restores the functionality I expect, but it *shouldn't* be this way because SILE should accept glues for these settings.

**Comment by alerque** [comment]
Note the fix for this is dependent on [the fix for issue](https://github.com/sile-typesetter/sile/issues/838) in SILE while will be in 0.10.4 or can be used from the *master* branch now.
